package com.service;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;



public interface LibUserService extends UserService{
	/**
	 * 
	 * @param book
	 * 
	 * @return book (inserted book with ID generated by database, if return is
	 *         null then fail)
	 */
	public  ArrayList<HashMap<String, Object>> add_to_checkoutList(ArrayList<HashMap<String, Object>> check_out_list,int bookId,String bookName,String bookISBN);
    public  ArrayList<HashMap<String, Object>> delete_checkout(ArrayList<HashMap<String, Object>> check_out_list,int checkoutId);
    public  HashMap<String, Object> get_book_order_info(int bookId,String bookName,String bookISBN);
	public  void submit_checkout(ArrayList<HashMap<String, Object>> check_out_list,int userId,int userQuota);
	public void submit_pre_order(int bookId,int userId);
	public ArrayList<HashMap<String, Object>> get_my_loanRecord(int userId);
	 public void returnBook(int bookId,int userId);
	 public void cancel_preOrder(int bookId,int userId);
	
}
